[samples]
# number of samples to generate
samples_number = 5000

# end value of number density until which to do the GPR, units in n_sat
n_end = 30
# how many points should the GPR return
n_points = 200

# starting and ending value of chemical potential mu for pqcd calculation in GeV
mu_start = 2.35
mu_end = 2.75

# Whether to convert phi&n to sound speed squared, pressure and energy density
convert_eos = true

# Whether to return samples in pressure/energy density + sound speed squared only or in phi/numdens too. Only in effect if convert_eos set to 'true'
return_only_eos = true

# Whether to check if connection to pQCD possible, and reject ones that do not connect. If eos is not converted, it is set to false regardless of user choice.

return_connecting = true

# Whether to return the renormalisation scale X for each sample, useful for matching pQCD given edens & pressure. if pQCD matching is set to true (and eos converted), this is turned to false
return_normscale = true

[output]
# where to save .npy file
# phi samples saved with "_phi", pressure-energydensity saved with "_eos"
directory = "results/eos_samples"
filename = "30nsConnecting"
