# all fields are compulsory
[input]
path = "/home/.../eos_directory" # do not include the ending /
filename = "eos_filename"        # do not include the extension ".npy"

[settings]
tov_iters = 500         # number of points in  MR/tidal curve
kind = "Tidal"          # "MR" only or including "Tidal". "Debug" returns m(r), p(r), y(r) for p_core
return_unstable = false # unstable branch returned as well if set to true
p_core = 300.0          # in MeV/fmÂ³. only required if kind = "Debug"

[output]
sort_nmma = false                    # whether to sort eos and mr&tidal curve sets in ascending order of lambda_1.4, useful for parameter estimation runs
out_type = "npy"                     # whether to return mr curves as "npy" file, as a singular "dat" file per eos, or "both"
path = "/home/.../results_directory" # do not include the ending /
filename = "filename"                # do not include the extension ".npy" or ".dat"
