# all fields are compulsory
[input]
path = "/home/sam/thesis/thesiscode/results/testing" # do not include the ending /
filename = "10_eos" # do not include the extension ".npy"

[settings]
tov_iters = 500 # number of points in  MR/tidal curve
kind = "Tidal" # "MR" only or including "Tidal". "Debug" returns m(r), p(r), y(r) for p_core
p_core = 300.0 # in MeV/fmÂ³. only required if kind = "Debug"

[profile]



[output]
path = "/home/sam/thesis/thesiscode/results/tov_res" # do not include the ending /
filename = "10_eos" # do not include the extension ".npy"
